### ISSUE TITLE
unable to get some customize attributes when exporting custom entity type

### ISSUE THREAD

**Issue by rheman** [ColdTrick/csv_exporter#11]
This plugin is amazin. Great job

But I have some troubles.

I have created and elgg plugin.

In my start.php under the init function I registered my entity type as followed.
elgg_register_entity_type("object", "tranings");

I create and save object as follwed.

```
$education = new ElggObject();
$education->subtype = "tranings";

$education->container_guid = $user_guid;
$education->owner_guid = $user_guid;
$education->title = htmlentities($school);
$education->description = htmlentities($trainingd);
$education->school = htmlentities($school);
$education->diploma = htmlentities($diploma);

$education->access_id = $accesslevel_education;
$education_guids[] = $education->save();
```

Everything works perfectly. I can retrieve my object and update it as needed.

But when I try to export my entity using your plugin, the following attributes are not available under "**Which attributes do you wish to export"**

```
$education->school
$education->diploma
```

But the following attributes are available.

```
$education->container_guid
$education->title
$education->description
```

So I dont know what I did wrong when creating.

I need help.

Best regard.

**Comment by jeabakker** [comment]
`school` and `diploma` aren't registered as exportable. Have a look at the [Readme.md](https://github.com/ColdTrick/csv_exporter#developers) how to make it exportable

To see an example
Registration
https://github.com/ColdTrick/static/blob/master/start.php#L72-L79
Export code
https://github.com/ColdTrick/static/blob/master/classes/ColdTrick/StaticPages/CSVExporter.php

**Comment by rheman** [comment]
thanks a lot
