### ISSUE TITLE
Why are semicolons inserted?

### ISSUE THREAD

**Issue by ewinslow** [ColdTrick/csv_exporter#4]
It's called CSV => Comma-separated-values. Are semi-colons and commas interchangeable? Google sheets doesn't seem to recognize them

**Comment by jdalsem** [comment]
Good point! You must be from America :) In Europe we have this problem with Excel: https://hotware.wordpress.com/2009/12/16/trouble-with-opening-csv-files-with-excel-the-comma-and-semicolon-issue-in-excel-due-to-regional-settings-for-europe/

Adding a setting to control delimiter (and text separator) would be nice

**Comment by jdalsem** [comment]
Google should however also be able to open CSV with other delimiters i guess
