### ISSUE TITLE
Allow exporting file/photo content

### ISSUE THREAD

**Issue by ewinslow** [ColdTrick/csv_exporter#5]
It's possible to get photo metadata, but not the photo itself. Being able to export the photo would be great. Perhaps could be done as a `data:` uri.

**Comment by jdalsem** [comment]
Feel free to add a PR

**Comment by jeabakker** [comment]
if you need it for some content you can add this ability by using the hooks, or do you really need it as basic functionality

**Comment by ewinslow** [comment]
I guess I'm wondering how else one would be expected to get photos or file content?

**Comment by jdalsem** [comment]
Maybe a reference to a file (like a download link) makes more sense. CSV is not intended to store images/files. It will not be added to this plugin
