### ISSUE TITLE
No buttons appear...

### ISSUE THREAD

**Issue by siteleas** [ColdTrick/csv_exporter#7]
Hi there. Thanks for making this plugin for Elgg! Although, I have to say, I have not been able to do much with it yet. When I go to the Administer section and then click Utilities, and then CSV exporter, I get the following:

Utilities : CSV Exporter
What do you wish to export <populated dropdown list>

First select what you wish to export

That's all that appears. No action buttons appear and I am therefor not able to use the export functionality that your plugin provides. Please let me know how to diagnose and resolve this issue. ;-)

Thanks

**Comment by siteleas** [comment]
I discovered, by using the firebug browser plugin, that one of the Elgg plugins that was installed in Elgg was somehow conflicting and causing the javascript events not to fire. Hence when a selection was made in the dropdown box no further actions were carried out. Perhaps a fallback of having buttons to launch actions would be nice (in the event that javascript events are disabled).

**Comment by jdalsem** [comment]
This plugin currently assumes that javascript is available. You are already unable to reach the menu item if javascript is disabled...
