### ISSUE TITLE
Export Group with its associated users

### ISSUE THREAD

**Issue by Billaboong** [ColdTrick/csv_exporter#8]
How can I export a group with all its users together and not separately?

**Comment by jdalsem** [comment]
What do you mean with 'together'?

**Comment by jdalsem** [comment]
What do you mean with 'together'?

**Comment by Billaboong** [comment]
For example if I have a group named github which has 20 members I wanted if I can get a csv file with two columns:groupname,users.The groupname column will have github and the user column will have all the 20 users separated by a delimiter

**Comment by jdalsem** [comment]
Closed in favor of #9
